name: Deploy to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug - list files
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -type f -name "package.json" -o -name "yarn.lock"

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install deps
        working-directory: back2front
        run: yarn install --frozen-lockfile

      - name: Build
        working-directory: back2front
        run: yarn build

      - name: SPA fallback
        run: cp back2front/build/index.html back2front/build/404.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: back2front/build
